apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mploin
  name: mploin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mploin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mploin
    spec:
      containers:
      - image: gswain3316/mploin:1.0.0
        name: mploin
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ploin
  name: ploin
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: ploin
  type: ClusterIP
status:
  loadBalancer: {}
